const heading = document.querySelector('h1');
console.log(heading);
const par = document.querySelectorAll('p');
console.log(par);
const monkey = document.querySelector('.test');
console.log(monkey);
const monkey1 = monkey.querySelector('#test');
console.log(monkey1);
const apple = document.createElement('ul');
console.log(object);
